### ISSUE TITLE
RFE: Divide FAILED tests into ERROR and FAIL

### ISSUE THREAD

**Issue by rplevka** [omaciel/qpd#6]
The jenkins actually recognizes several test results, which are later being aggregated to basic 3 [passed,failed,skipped].

For failed, there are ERROR, FAIL and REGRESSION
- it would be nice to distinguish ERROR from FAIL as ERROR usually means error in our testing suite - it would be nice to see that separated in the charts. From that, one could better tell, whether it is the test suite which is getting better or the tested product itself

**Comment by omaciel** [comment]
![screenshot 2016-08-26 12 11 50](https://cloud.githubusercontent.com/assets/53362/18012163/4fd1ef1a-6b86-11e6-8b06-37f45e558c4a.png)

@rplevka how about this?

**Comment by rplevka** [comment]
perfect

**Comment by omaciel** [comment]
Git pull

**Comment by omaciel** [comment]
@rplevka I have included `Error` now as a column and it shows up on charts as well. git pull and let me know what you think.
